[workspace]
resolver = "2"

members = [
    "move-types",
    "move-binding",
    "move-binding-derive"
]

[workspace.dependencies]
serde = { version = "1.0.228" }

thiserror = "2.0.17"
sui-sdk-types = { git = "https://github.com/mystenlabs/sui-rust-sdk", rev = "d8643443b523fb14873c3ea566a7b7f8146b34e8", features = ["serde"] }
sui-transaction-builder = { git = "https://github.com/mystenlabs/sui-rust-sdk", rev = "d8643443b523fb14873c3ea566a7b7f8146b34e8" }
sui-graphql = { git = "https://github.com/mystenlabs/sui-rust-sdk", rev = "d8643443b523fb14873c3ea566a7b7f8146b34e8" }
sui-graphql-macros = { git = "https://github.com/mystenlabs/sui-rust-sdk", rev = "d8643443b523fb14873c3ea566a7b7f8146b34e8" }
sui-rpc = { git = "https://github.com/mystenlabs/sui-rust-sdk", rev = "d8643443b523fb14873c3ea566a7b7f8146b34e8" }
